/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['[_nghost-%COMP%]{\r\n    display: block;\r\n}\r\n.media[_ngcontent-%COMP%]\r\n{\r\n    \r\n    margin: 20px 0;\r\n    padding:30px;\r\n}\r\n.dp[_ngcontent-%COMP%]\r\n{\r\n    border:10px solid #eee;\r\n    transition: all 0.2s ease-in-out;\r\n}\r\n.dp[_ngcontent-%COMP%]:hover\r\n{\r\n    border:2px solid #eee;\r\n    transform:rotate(360deg);\r\n    -ms-transform:rotate(360deg);\r\n    -webkit-transform:rotate(360deg);\r\n    \r\n}'];