/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../app/app.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/element_ref';
import * as import9 from '@angular/core/src/zone/ng_zone';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../app/demos/tick.component';
import * as import13 from '@angular/router/src/directives/router_link';
import * as import14 from '@angular/router/src/directives/router_link_active';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '@angular/router/src/directives/router_outlet';
import * as import17 from './demos/tick.component.ngfactory';
import * as import18 from '@angular/router/src/router';
import * as import19 from '@angular/router/src/router_state';
import * as import20 from '@angular/common/src/location/location_strategy';
import * as import21 from '@angular/router/src/router_outlet_map';
import * as import22 from '@angular/core/src/linker/component_factory_resolver';
import * as import23 from '@angular/core/src/security';
var renderType_AppComponent_Host:import0.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AppComponent_0_4:import3.AppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-app',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new import3.AppComponent(new import8.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import9.NgZone));
    this._appEl_0.initComponent(this._AppComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._AppComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import11.ComponentFactory<import3.AppComponent> = new import11.ComponentFactory<import3.AppComponent>('my-app',viewFactory_AppComponent_Host0,import3.AppComponent);
const styles_AppComponent:any[] = ['[_nghost-%COMP%]{display: block}'];
var renderType_AppComponent:import0.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import3.AppComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _TickComponent_3_4:import12.TickComponent;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _RouterLinkWithHref_8_3:import13.RouterLinkWithHref;
  _RouterLinkActive_8_4:import14.RouterLinkActive;
  _query_RouterLink_8_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_8_1:import15.QueryList<any>;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _RouterLinkWithHref_11_3:import13.RouterLinkWithHref;
  _RouterLinkActive_11_4:import14.RouterLinkActive;
  _query_RouterLink_11_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_11_1:import15.QueryList<any>;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _RouterLinkWithHref_14_3:import13.RouterLinkWithHref;
  _RouterLinkActive_14_4:import14.RouterLinkActive;
  _query_RouterLink_14_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_14_1:import15.QueryList<any>;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _RouterLinkWithHref_17_3:import13.RouterLinkWithHref;
  _RouterLinkActive_17_4:import14.RouterLinkActive;
  _query_RouterLink_17_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_17_1:import15.QueryList<any>;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _RouterLinkWithHref_20_3:import13.RouterLinkWithHref;
  _RouterLinkActive_20_4:import14.RouterLinkActive;
  _query_RouterLink_20_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_20_1:import15.QueryList<any>;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _RouterLinkWithHref_23_3:import13.RouterLinkWithHref;
  _RouterLinkActive_23_4:import14.RouterLinkActive;
  _query_RouterLink_23_0:import15.QueryList<any>;
  _query_RouterLinkWithHref_23_1:import15.QueryList<any>;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _RouterOutlet_28_5:import16.RouterOutlet;
  _text_29:any;
  _text_30:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','container-fluid');
    this.renderer.setElementAttribute(this._el_1,'style','max-width:800px');
    this._text_2 = this.renderer.createText(this._el_1,'\n         ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'tick',(null as any));
    this._appEl_3 = new import2.AppElement(3,1,this,this._el_3);
    var compView_3:any = import17.viewFactory_TickComponent0(this.viewUtils,this.injector(3),this._appEl_3);
    this._TickComponent_3_4 = new import12.TickComponent(new import8.ElementRef(this._el_3),this.renderer,this.parentInjector.get(import9.NgZone),compView_3.ref);
    this._appEl_3.initComponent(this._TickComponent_3_4,([] as any[]),compView_3);
    compView_3.create(this._TickComponent_3_4,([] as any[]),(null as any));
    this._text_4 = this.renderer.createText(this._el_1,'\n         ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_1,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','center-block');
    this._text_6 = this.renderer.createText(this._el_5,' Change detection demos',(null as any));
    this._text_7 = this.renderer.createText(this._el_1,'\n        \n        ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_1,'a',(null as any));
    this.renderer.setElementAttribute(this._el_8,'routerLink','/home');
    this.renderer.setElementAttribute(this._el_8,'routerLinkActive','active');
    this._RouterLinkWithHref_8_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import18.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._RouterLinkActive_8_4 = new import14.RouterLinkActive(this.parentInjector.get(import18.Router),new import8.ElementRef(this._el_8),this.renderer);
    this._query_RouterLink_8_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_8_1 = new import15.QueryList<any>();
    this._text_9 = this.renderer.createText(this._el_8,'Home',(null as any));
    this._text_10 = this.renderer.createText(this._el_1,' |\n         \n         ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_1,'a',(null as any));
    this.renderer.setElementAttribute(this._el_11,'routerLink','/counter');
    this.renderer.setElementAttribute(this._el_11,'routerLinkActive','active');
    this._RouterLinkWithHref_11_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import18.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._RouterLinkActive_11_4 = new import14.RouterLinkActive(this.parentInjector.get(import18.Router),new import8.ElementRef(this._el_11),this.renderer);
    this._query_RouterLink_11_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_11_1 = new import15.QueryList<any>();
    this._text_12 = this.renderer.createText(this._el_11,'Counter',(null as any));
    this._text_13 = this.renderer.createText(this._el_1,' |\n         ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_1,'a',(null as any));
    this.renderer.setElementAttribute(this._el_14,'routerLink','/board');
    this.renderer.setElementAttribute(this._el_14,'routerLinkActive','active');
    this._RouterLinkWithHref_14_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import18.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._RouterLinkActive_14_4 = new import14.RouterLinkActive(this.parentInjector.get(import18.Router),new import8.ElementRef(this._el_14),this.renderer);
    this._query_RouterLink_14_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_14_1 = new import15.QueryList<any>();
    this._text_15 = this.renderer.createText(this._el_14,'Board',(null as any));
    this._text_16 = this.renderer.createText(this._el_1,' |\n         ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_1,'a',(null as any));
    this.renderer.setElementAttribute(this._el_17,'routerLink','/accordion');
    this.renderer.setElementAttribute(this._el_17,'routerLinkActive','active');
    this._RouterLinkWithHref_17_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import18.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._RouterLinkActive_17_4 = new import14.RouterLinkActive(this.parentInjector.get(import18.Router),new import8.ElementRef(this._el_17),this.renderer);
    this._query_RouterLink_17_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_17_1 = new import15.QueryList<any>();
    this._text_18 = this.renderer.createText(this._el_17,'Accordion',(null as any));
    this._text_19 = this.renderer.createText(this._el_1,' |\n\n         ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_1,'a',(null as any));
    this.renderer.setElementAttribute(this._el_20,'routerLink','/onpush');
    this.renderer.setElementAttribute(this._el_20,'routerLinkActive','active');
    this._RouterLinkWithHref_20_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import18.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._RouterLinkActive_20_4 = new import14.RouterLinkActive(this.parentInjector.get(import18.Router),new import8.ElementRef(this._el_20),this.renderer);
    this._query_RouterLink_20_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_20_1 = new import15.QueryList<any>();
    this._text_21 = this.renderer.createText(this._el_20,'OnPush',(null as any));
    this._text_22 = this.renderer.createText(this._el_1,' |\n         ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_1,'a',(null as any));
    this.renderer.setElementAttribute(this._el_23,'routerLink','/ondirty');
    this.renderer.setElementAttribute(this._el_23,'routerLinkActive','active');
    this._RouterLinkWithHref_23_3 = new import13.RouterLinkWithHref(this.parentInjector.get(import18.Router),this.parentInjector.get(import19.ActivatedRoute),this.parentInjector.get(import20.LocationStrategy));
    this._RouterLinkActive_23_4 = new import14.RouterLinkActive(this.parentInjector.get(import18.Router),new import8.ElementRef(this._el_23),this.renderer);
    this._query_RouterLink_23_0 = new import15.QueryList<any>();
    this._query_RouterLinkWithHref_23_1 = new import15.QueryList<any>();
    this._text_24 = this.renderer.createText(this._el_23,'OnDirty',(null as any));
    this._text_25 = this.renderer.createText(this._el_1,' |\n         \n         \n         ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_1,'hr',(null as any));
    this._text_27 = this.renderer.createText(this._el_1,'\n         ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_1,'router-outlet',(null as any));
    this._appEl_28 = new import2.AppElement(28,1,this,this._el_28);
    this._RouterOutlet_28_5 = new import16.RouterOutlet(this.parentInjector.get(import21.RouterOutletMap),this._appEl_28.vcRef,this.parentInjector.get(import22.ComponentFactoryResolver),(null as any));
    this._text_29 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_30 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_17,'click',this.eventHandler(this._handle_click_17_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_20,'click',this.eventHandler(this._handle_click_20_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.TickComponent) && (3 === requestNodeIndex))) { return this._TickComponent_3_4; }
    if (((token === import13.RouterLinkWithHref) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._RouterLinkWithHref_8_3; }
    if (((token === import14.RouterLinkActive) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._RouterLinkActive_8_4; }
    if (((token === import13.RouterLinkWithHref) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkWithHref_11_3; }
    if (((token === import14.RouterLinkActive) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkActive_11_4; }
    if (((token === import13.RouterLinkWithHref) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._RouterLinkWithHref_14_3; }
    if (((token === import14.RouterLinkActive) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._RouterLinkActive_14_4; }
    if (((token === import13.RouterLinkWithHref) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._RouterLinkWithHref_17_3; }
    if (((token === import14.RouterLinkActive) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._RouterLinkActive_17_4; }
    if (((token === import13.RouterLinkWithHref) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._RouterLinkWithHref_20_3; }
    if (((token === import14.RouterLinkActive) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._RouterLinkActive_20_4; }
    if (((token === import13.RouterLinkWithHref) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._RouterLinkWithHref_23_3; }
    if (((token === import14.RouterLinkActive) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._RouterLinkActive_23_4; }
    if (((token === import16.RouterOutlet) && (28 === requestNodeIndex))) { return this._RouterOutlet_28_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TickComponent_3_4.ngOnInit(); }
    if (!throwOnChange) { this._TickComponent_3_4.ngDoCheck(); }
    changes = (null as any);
    const currVal_1:any = '/home';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_8_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_8_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_3:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._RouterLinkActive_8_4.routerLinkActive = currVal_3;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_3,currVal_3);
      this._expr_3 = currVal_3;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_8_4.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_5:any = '/counter';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._RouterLinkWithHref_11_3.routerLink = currVal_5;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_5,currVal_5);
      this._expr_5 = currVal_5;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_11_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_7:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RouterLinkActive_11_4.routerLinkActive = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_11_4.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_9:any = '/board';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._RouterLinkWithHref_14_3.routerLink = currVal_9;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_9,currVal_9);
      this._expr_9 = currVal_9;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_14_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_11:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._RouterLinkActive_14_4.routerLinkActive = currVal_11;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_11,currVal_11);
      this._expr_11 = currVal_11;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_14_4.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_13:any = '/accordion';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._RouterLinkWithHref_17_3.routerLink = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_17_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_15:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._RouterLinkActive_17_4.routerLinkActive = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_17_4.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_17:any = '/onpush';
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._RouterLinkWithHref_20_3.routerLink = currVal_17;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_17,currVal_17);
      this._expr_17 = currVal_17;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_20_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_19:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._RouterLinkActive_20_4.routerLinkActive = currVal_19;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_19,currVal_19);
      this._expr_19 = currVal_19;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_20_4.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_21:any = '/ondirty';
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._RouterLinkWithHref_23_3.routerLink = currVal_21;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import7.SimpleChange(this._expr_21,currVal_21);
      this._expr_21 = currVal_21;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_23_3.ngOnChanges(changes); }
    changes = (null as any);
    const currVal_23:any = 'active';
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._RouterLinkActive_23_4.routerLinkActive = currVal_23;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLinkActive'] = new import7.SimpleChange(this._expr_23,currVal_23);
      this._expr_23 = currVal_23;
    }
    if ((changes !== (null as any))) { this._RouterLinkActive_23_4.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_8_0.dirty) {
        this._query_RouterLink_8_0.reset(([] as any[]));
        this._RouterLinkActive_8_4.links = this._query_RouterLink_8_0;
        this._query_RouterLink_8_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_8_1.dirty) {
        this._query_RouterLinkWithHref_8_1.reset([this._RouterLinkWithHref_8_3]);
        this._RouterLinkActive_8_4.linksWithHrefs = this._query_RouterLinkWithHref_8_1;
        this._query_RouterLinkWithHref_8_1.notifyOnChanges();
      }
      if (this._query_RouterLink_11_0.dirty) {
        this._query_RouterLink_11_0.reset(([] as any[]));
        this._RouterLinkActive_11_4.links = this._query_RouterLink_11_0;
        this._query_RouterLink_11_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_11_1.dirty) {
        this._query_RouterLinkWithHref_11_1.reset([this._RouterLinkWithHref_11_3]);
        this._RouterLinkActive_11_4.linksWithHrefs = this._query_RouterLinkWithHref_11_1;
        this._query_RouterLinkWithHref_11_1.notifyOnChanges();
      }
      if (this._query_RouterLink_14_0.dirty) {
        this._query_RouterLink_14_0.reset(([] as any[]));
        this._RouterLinkActive_14_4.links = this._query_RouterLink_14_0;
        this._query_RouterLink_14_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_14_1.dirty) {
        this._query_RouterLinkWithHref_14_1.reset([this._RouterLinkWithHref_14_3]);
        this._RouterLinkActive_14_4.linksWithHrefs = this._query_RouterLinkWithHref_14_1;
        this._query_RouterLinkWithHref_14_1.notifyOnChanges();
      }
      if (this._query_RouterLink_17_0.dirty) {
        this._query_RouterLink_17_0.reset(([] as any[]));
        this._RouterLinkActive_17_4.links = this._query_RouterLink_17_0;
        this._query_RouterLink_17_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_17_1.dirty) {
        this._query_RouterLinkWithHref_17_1.reset([this._RouterLinkWithHref_17_3]);
        this._RouterLinkActive_17_4.linksWithHrefs = this._query_RouterLinkWithHref_17_1;
        this._query_RouterLinkWithHref_17_1.notifyOnChanges();
      }
      if (this._query_RouterLink_20_0.dirty) {
        this._query_RouterLink_20_0.reset(([] as any[]));
        this._RouterLinkActive_20_4.links = this._query_RouterLink_20_0;
        this._query_RouterLink_20_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_20_1.dirty) {
        this._query_RouterLinkWithHref_20_1.reset([this._RouterLinkWithHref_20_3]);
        this._RouterLinkActive_20_4.linksWithHrefs = this._query_RouterLinkWithHref_20_1;
        this._query_RouterLinkWithHref_20_1.notifyOnChanges();
      }
      if (this._query_RouterLink_23_0.dirty) {
        this._query_RouterLink_23_0.reset(([] as any[]));
        this._RouterLinkActive_23_4.links = this._query_RouterLink_23_0;
        this._query_RouterLink_23_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_23_1.dirty) {
        this._query_RouterLinkWithHref_23_1.reset([this._RouterLinkWithHref_23_3]);
        this._RouterLinkActive_23_4.linksWithHrefs = this._query_RouterLinkWithHref_23_1;
        this._query_RouterLinkWithHref_23_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_8_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_11_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_14_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_17_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_20_4.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_23_4.ngAfterContentInit(); }
    }
    const currVal_2:any = this._RouterLinkWithHref_8_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_8,'href',this.viewUtils.sanitizer.sanitize(import23.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    const currVal_6:any = this._RouterLinkWithHref_11_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementProperty(this._el_11,'href',this.viewUtils.sanitizer.sanitize(import23.SecurityContext.URL,currVal_6));
      this._expr_6 = currVal_6;
    }
    const currVal_10:any = this._RouterLinkWithHref_14_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementProperty(this._el_14,'href',this.viewUtils.sanitizer.sanitize(import23.SecurityContext.URL,currVal_10));
      this._expr_10 = currVal_10;
    }
    const currVal_14:any = this._RouterLinkWithHref_17_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementProperty(this._el_17,'href',this.viewUtils.sanitizer.sanitize(import23.SecurityContext.URL,currVal_14));
      this._expr_14 = currVal_14;
    }
    const currVal_18:any = this._RouterLinkWithHref_20_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementProperty(this._el_20,'href',this.viewUtils.sanitizer.sanitize(import23.SecurityContext.URL,currVal_18));
      this._expr_18 = currVal_18;
    }
    const currVal_22:any = this._RouterLinkWithHref_23_3.href;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementProperty(this._el_23,'href',this.viewUtils.sanitizer.sanitize(import23.SecurityContext.URL,currVal_22));
      this._expr_22 = currVal_22;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_8_3.ngOnDestroy();
    this._RouterLinkActive_8_4.ngOnDestroy();
    this._RouterLinkWithHref_11_3.ngOnDestroy();
    this._RouterLinkActive_11_4.ngOnDestroy();
    this._RouterLinkWithHref_14_3.ngOnDestroy();
    this._RouterLinkActive_14_4.ngOnDestroy();
    this._RouterLinkWithHref_17_3.ngOnDestroy();
    this._RouterLinkActive_17_4.ngOnDestroy();
    this._RouterLinkWithHref_20_3.ngOnDestroy();
    this._RouterLinkActive_20_4.ngOnDestroy();
    this._RouterLinkWithHref_23_3.ngOnDestroy();
    this._RouterLinkActive_23_4.ngOnDestroy();
    this._RouterOutlet_28_5.ngOnDestroy();
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_8_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_11_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_14_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_17_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_17_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_20_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RouterLinkWithHref_23_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}