/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/demos/tick.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/element_ref';
import * as import9 from '@angular/core/src/zone/ng_zone';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/core/src/linker/query_list';
var renderType_TickComponent_Host:import0.RenderComponentType = (null as any);
class _View_TickComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _TickComponent_0_4:import3.TickComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TickComponent_Host0,renderType_TickComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('tick',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_TickComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._TickComponent_0_4 = new import3.TickComponent(new import8.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import9.NgZone),compView_0.ref);
    this._appEl_0.initComponent(this._TickComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._TickComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.TickComponent) && (0 === requestNodeIndex))) { return this._TickComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._TickComponent_0_4.ngOnInit(); }
    if (!throwOnChange) { this._TickComponent_0_4.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_TickComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_TickComponent_Host === (null as any))) { (renderType_TickComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_TickComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const TickComponentNgFactory:import11.ComponentFactory<import3.TickComponent> = new import11.ComponentFactory<import3.TickComponent>('tick',viewFactory_TickComponent_Host0,import3.TickComponent);
const styles_TickComponent:any[] = ['.box[_ngcontent-%COMP%]{ \n            width : 10px;\n            height: 12px;\n            border: 1px solid black;\n            margin-right: 3px;\n        }\n        [_nghost-%COMP%]{\n            display: block;\n            position: absolute;\n            top: 8px;\n            right: 8px;\n            line-height:0px;\n        }\n        .notDisplay[_ngcontent-%COMP%]{\n            border: 1px solid black;    \n        }'];
var renderType_TickComponent:import0.RenderComponentType = (null as any);
class _View_TickComponent0 extends import1.AppView<import3.TickComponent> {
  _viewQuery_box_0:import12.QueryList<any>;
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_TickComponent0,renderType_TickComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_box_0 = new import12.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n   ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'style',' margin: auto;');
    this._text_2 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'button',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','box');
    this._text_4 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_1,'span',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_1,'\n   ',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_3,'click',this.eventHandler(this._handle_click_3_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._viewQuery_box_0.reset([new import8.ElementRef(this._el_3)]);
    this.context.boxElemRef = this._viewQuery_box_0.first;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import4.interpolate(1,'ticks: ',this.context.oldValue,' / s');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_6,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.setBorder()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_TickComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.TickComponent> {
  if ((renderType_TickComponent === (null as any))) { (renderType_TickComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_TickComponent,{})); }
  return new _View_TickComponent0(viewUtils,parentInjector,declarationEl);
}