/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../app/demos/counter/counter.component';
const styles_CounterComponent:any[] = ['[_nghost-%COMP%]{\n            display: block;\n            width: 50px; height: 50px;\n            border: 1px dotted black;\n            text-align: center;\n            vertical-align: middle;\n            margin: 8px;\n                        \n    }'];
export const RenderType_CounterComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_CounterComponent,
  data: {}
}
);
export function View_CounterComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),(null as any),[[
        (null as any),
        'click'
      ]
    ],(v,en,$event) => {
      var ad:boolean = true;
      var co:import1.CounterComponent = v.component;
      if (('click' === en)) {
        const pd_0:any = ((<any>co.onClick()) !== false);
        ad = (pd_0 && ad);
      }
      return ad;
    },(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.CounterComponent = v.component;
    const currVal_0:any = co.value;
    ck(v,2,0,currVal_0);
  });
}
function View_CounterComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'counter',([] as any[]),(null as any),(null as any),(null as any),View_CounterComponent_0,RenderType_CounterComponent)),
    import0.ɵdid(221184,(null as any),0,import1.CounterComponent,[
      import0.ElementRef,
      import0.Renderer2,
      import0.NgZone,
      import0.ChangeDetectorRef,
      import0.ApplicationRef
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const CounterComponentNgFactory:import0.ComponentFactory<import1.CounterComponent> = import0.ɵccf('counter',import1.CounterComponent,View_CounterComponent_Host_0,{
  isStart: 'isStart',
  isDetectChanges: 'isDetectChanges',
  value: 'value',
  ms: 'ms',
  isTick: 'isTick'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvRXlhbC9EZXNrdG9wL1BlcmZvcm1hbmNlIE9wdGltaXphdGlvbi9uZy1jb3Vyc2UoY2QpL2FwcC9kZW1vcy9jb3VudGVyL2NvdW50ZXIuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0V5YWwvRGVza3RvcC9QZXJmb3JtYW5jZSBPcHRpbWl6YXRpb24vbmctY291cnNlKGNkKS9hcHAvZGVtb3MvY291bnRlci9jb3VudGVyLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL0V5YWwvRGVza3RvcC9QZXJmb3JtYW5jZSBPcHRpbWl6YXRpb24vbmctY291cnNlKGNkKS9hcHAvZGVtb3MvY291bnRlci9jb3VudGVyLmNvbXBvbmVudC50cy5Db3VudGVyQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9FeWFsL0Rlc2t0b3AvUGVyZm9ybWFuY2UgT3B0aW1pemF0aW9uL25nLWNvdXJzZShjZCkvYXBwL2RlbW9zL2NvdW50ZXIvY291bnRlci5jb21wb25lbnQudHMuQ291bnRlckNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxkaXYgKGNsaWNrKT1cIm9uQ2xpY2soKVwiPnt7dmFsdWV9fTwvZGl2PlxuIiwiPGNvdW50ZXI+PC9jb3VudGVyPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtNQUNJO1FBQUE7UUFBQTtNQUFBO0lBQUE7TUFBQTtNQUFBO01BQUs7UUFBQTtRQUFBO01BQUE7TUFBTDtJQUFBO0lBQXlCO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFBZTs7OztJQUFmO0lBQUE7Ozs7O0lDRDdCO2dCQUFBOzs7Ozs7SUFBQTtLQUFBOzs7SUFBQTs7Ozs7Ozs7OzsifQ==
