/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/demos/counter/demo.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/element_ref';
import * as import9 from '@angular/core/src/zone/ng_zone';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/common/src/directives/ng_class';
import * as import13 from '@angular/common/src/directives/ng_if';
import * as import14 from '../../../../app/demos/counter/counter.component';
import * as import15 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import16 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from './counter.component.ngfactory';
import * as import19 from '@angular/core/src/application_ref';
var renderType_CounterDemoComponent_Host:import0.RenderComponentType = (null as any);
class _View_CounterDemoComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _CounterDemoComponent_0_4:import3.CounterDemoComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CounterDemoComponent_Host0,renderType_CounterDemoComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CounterDemoComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CounterDemoComponent_0_4 = new import3.CounterDemoComponent(new import8.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import9.NgZone),compView_0.ref);
    this._appEl_0.initComponent(this._CounterDemoComponent_0_4,[],compView_0);
    compView_0.create(this._CounterDemoComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.CounterDemoComponent) && (0 === requestNodeIndex))) { return this._CounterDemoComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_CounterDemoComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_CounterDemoComponent_Host === (null as any))) { (renderType_CounterDemoComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_CounterDemoComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const CounterDemoComponentNgFactory:import11.ComponentFactory<import3.CounterDemoComponent> = new import11.ComponentFactory<import3.CounterDemoComponent>('ng-component',viewFactory_CounterDemoComponent_Host0,import3.CounterDemoComponent);
const styles_CounterDemoComponent:any[] = ['[_nghost-%COMP%]{display: block;margin: 5px}'];
var renderType_CounterDemoComponent:import0.RenderComponentType = (null as any);
class _View_CounterDemoComponent0 extends import1.AppView<import3.CounterDemoComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _NgClass_6_3:import12.NgClass;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import13.NgIf;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _NgClass_11_3:import12.NgClass;
  _text_12:any;
  _anchor_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _TemplateRef_13_5:any;
  _NgIf_13_6:import13.NgIf;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _NgClass_16_3:import12.NgClass;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import2.AppElement;
  _TemplateRef_18_5:any;
  _NgIf_18_6:import13.NgIf;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import2.AppElement;
  _CounterComponent_25_4:import14.CounterComponent;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  /*private*/ _expr_1:any;
  _map_0:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  _map_1:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  _map_2:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CounterDemoComponent0,renderType_CounterDemoComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'      \n     ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'h4',(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'Counter component',(null as any));
    this._text_5 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_1,'button',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','btn');
    this._NgClass_6_3 = new import12.NgClass(this.parentInjector.get(import15.IterableDiffers),this.parentInjector.get(import16.KeyValueDiffers),new import8.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_8 = new import2.AppElement(8,6,this,this._anchor_8);
    this._TemplateRef_8_5 = new import17.TemplateRef_(this._appEl_8,viewFactory_CounterDemoComponent1);
    this._NgIf_8_6 = new import13.NgIf(this._appEl_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(this._el_6,'Ticks\n      ',(null as any));
    this._text_10 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_1,'button',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','btn');
    this._NgClass_11_3 = new import12.NgClass(this.parentInjector.get(import15.IterableDiffers),this.parentInjector.get(import16.KeyValueDiffers),new import8.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._anchor_13 = this.renderer.createTemplateAnchor(this._el_11,(null as any));
    this._appEl_13 = new import2.AppElement(13,11,this,this._anchor_13);
    this._TemplateRef_13_5 = new import17.TemplateRef_(this._appEl_13,viewFactory_CounterDemoComponent2);
    this._NgIf_13_6 = new import13.NgIf(this._appEl_13.vcRef,this._TemplateRef_13_5);
    this._text_14 = this.renderer.createText(this._el_11,' Detect Changes\n      ',(null as any));
    this._text_15 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_1,'button',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','btn');
    this._NgClass_16_3 = new import12.NgClass(this.parentInjector.get(import15.IterableDiffers),this.parentInjector.get(import16.KeyValueDiffers),new import8.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._appEl_18 = new import2.AppElement(18,16,this,this._anchor_18);
    this._TemplateRef_18_5 = new import17.TemplateRef_(this._appEl_18,viewFactory_CounterDemoComponent3);
    this._NgIf_18_6 = new import13.NgIf(this._appEl_18.vcRef,this._TemplateRef_18_5);
    this._text_19 = this.renderer.createText(this._el_16,' Border\n      ',(null as any));
    this._text_20 = this.renderer.createText(this._el_1,'            \n      ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_1,'br',(null as any));
    this._text_22 = this.renderer.createText(this._el_1,' \n      ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_1,'hr',(null as any));
    this._text_24 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_25 = this.renderer.createElement(this._el_1,'counter',(null as any));
    this._appEl_25 = new import2.AppElement(25,1,this,this._el_25);
    var compView_25:any = import18.viewFactory_CounterComponent0(this.viewUtils,this.injector(25),this._appEl_25);
    this._CounterComponent_25_4 = new import14.CounterComponent(new import8.ElementRef(this._el_25),this.renderer,this.parentInjector.get(import9.NgZone),compView_25.ref,this.parentInjector.get(import19.ApplicationRef));
    this._appEl_25.initComponent(this._CounterComponent_25_4,[],compView_25);
    this._text_26 = this.renderer.createText((null as any),'      \n      ',(null as any));
    compView_25.create(this._CounterComponent_25_4,[],(null as any));
    this._text_27 = this.renderer.createText(this._el_1,'\n      \n      ',(null as any));
    this._text_28 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_29 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_6,'click',this.eventHandler(this._handle_click_6_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'btn-warning': p0,
        'btn-success': p1
      }
      ;
    });
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._map_1 = import4.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'btn-warning': p0,
        'btn-success': p1
      }
      ;
    });
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_16,'click',this.eventHandler(this._handle_click_16_0.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._map_2 = import4.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'btn-warning': p0,
        'btn-success': p1
      }
      ;
    });
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._anchor_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import13.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6; }
    if (((token === import12.NgClass) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._NgClass_6_3; }
    if (((token === import17.TemplateRef) && (13 === requestNodeIndex))) { return this._TemplateRef_13_5; }
    if (((token === import13.NgIf) && (13 === requestNodeIndex))) { return this._NgIf_13_6; }
    if (((token === import12.NgClass) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._NgClass_11_3; }
    if (((token === import17.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import13.NgIf) && (18 === requestNodeIndex))) { return this._NgIf_18_6; }
    if (((token === import12.NgClass) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._NgClass_16_3; }
    if (((token === import14.CounterComponent) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._CounterComponent_25_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = 'btn';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgClass_6_3.klass = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._map_0(this.context.isTick,!this.context.isTick);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgClass_6_3.ngClass = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgClass_6_3.ngDoCheck(); }
    const currVal_3:boolean = !this.context.isTick;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgIf_8_6.ngIf = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = 'btn';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._NgClass_11_3.klass = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._map_1(!this.context.isDetectChanges,this.context.isDetectChanges);
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgClass_11_3.ngClass = currVal_6;
      this._expr_6 = currVal_6;
    }
    if (!throwOnChange) { this._NgClass_11_3.ngDoCheck(); }
    const currVal_7:boolean = !this.context.isDetectChanges;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgIf_13_6.ngIf = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_9:any = 'btn';
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgClass_16_3.klass = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._map_2(this.context.isBorder,!this.context.isBorder);
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgClass_16_3.ngClass = currVal_10;
      this._expr_10 = currVal_10;
    }
    if (!throwOnChange) { this._NgClass_16_3.ngDoCheck(); }
    const currVal_11:boolean = !this.context.isBorder;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgIf_18_6.ngIf = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this.context.isDetectChanges;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._CounterComponent_25_4.isDetectChanges = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = 100;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._CounterComponent_25_4.value = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = 10;
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._CounterComponent_25_4.ms = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.context.isTick;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._CounterComponent_25_4.isTick = currVal_15;
      this._expr_15 = currVal_15;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._CounterComponent_25_4.ngOnDestroy();
  }
  private _handle_click_6_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.isTick = !this.context.isTick)) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.isDetectChanges = !this.context.isDetectChanges)) !== false);
    return (true && pd_0);
  }
  private _handle_click_16_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.isBorder = !this.context.isBorder)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_CounterDemoComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.CounterDemoComponent> {
  if ((renderType_CounterDemoComponent === (null as any))) { (renderType_CounterDemoComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_CounterDemoComponent,{})); }
  return new _View_CounterDemoComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_CounterDemoComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CounterDemoComponent1,renderType_CounterDemoComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'No',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_CounterDemoComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_CounterDemoComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_CounterDemoComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CounterDemoComponent2,renderType_CounterDemoComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'No',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_CounterDemoComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_CounterDemoComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_CounterDemoComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_CounterDemoComponent3,renderType_CounterDemoComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'No',(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_CounterDemoComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_CounterDemoComponent3(viewUtils,parentInjector,declarationEl);
}