/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/demos/detach/users-demo.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/element_ref';
import * as import9 from '@angular/core/src/zone/ng_zone';
import * as import10 from '@angular/http/src/http';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/common/src/directives/ng_class';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '@angular/common/src/directives/ng_for';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '../../../../app/demos/detach/user.component';
import * as import20 from './user.component.ngfactory';
var renderType_UsersDemoComponent_Host:import0.RenderComponentType = (null as any);
class _View_UsersDemoComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UsersDemoComponent_0_4:import3.UsersDemoComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UsersDemoComponent_Host0,renderType_UsersDemoComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UsersDemoComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UsersDemoComponent_0_4 = new import3.UsersDemoComponent(new import8.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import9.NgZone),compView_0.ref,this.parentInjector.get(import10.Http));
    this._appEl_0.initComponent(this._UsersDemoComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._UsersDemoComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UsersDemoComponent) && (0 === requestNodeIndex))) { return this._UsersDemoComponent_0_4; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._UsersDemoComponent_0_4.ngOnDestroy();
  }
}
function viewFactory_UsersDemoComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UsersDemoComponent_Host === (null as any))) { (renderType_UsersDemoComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_UsersDemoComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UsersDemoComponentNgFactory:import12.ComponentFactory<import3.UsersDemoComponent> = new import12.ComponentFactory<import3.UsersDemoComponent>('ng-component',viewFactory_UsersDemoComponent_Host0,import3.UsersDemoComponent);
const styles_UsersDemoComponent:any[] = ['[_nghost-%COMP%]{display: block;}\n    .short[_ngcontent-%COMP%]{\n        width: 70px;\n    }'];
var renderType_UsersDemoComponent:import0.RenderComponentType = (null as any);
class _View_UsersDemoComponent0 extends import1.AppView<import3.UsersDemoComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _NgClass_11_3:import13.NgClass;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _NgClass_14_3:import13.NgClass;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import14.NgIf;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _NgClass_19_3:import13.NgClass;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TemplateRef_24_5:any;
  _NgFor_24_6:import15.NgFor;
  _text_25:any;
  _text_26:any;
  /*private*/ _expr_2:any;
  _map_0:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  _map_1:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_10:any;
  _map_2:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UsersDemoComponent0,renderType_UsersDemoComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'P',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','desc');
    this._text_4 = this.renderer.createText(this._el_3,'\n        This demo shows how to reduce the amount of expressions that need to \n        calculate every tick by using the on push strategy.  \n    ',(null as any));
    this._text_5 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_1,'input',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','short');
    this.renderer.setElementAttribute(this._el_6,'type','number');
    this.renderer.setElementAttribute(this._el_6,'value','1000');
    this._text_7 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_1,'button',(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'Load',(null as any));
    this._text_10 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_1,'button',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','btn');
    this._NgClass_11_3 = new import13.NgClass(this.parentInjector.get(import16.IterableDiffers),this.parentInjector.get(import17.KeyValueDiffers),new import8.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_1,'\n     ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_1,'button',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','btn');
    this._NgClass_14_3 = new import13.NgClass(this.parentInjector.get(import16.IterableDiffers),this.parentInjector.get(import17.KeyValueDiffers),new import8.ElementRef(this._el_14),this.renderer);
    this._text_15 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._appEl_16 = new import2.AppElement(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import18.TemplateRef_(this._appEl_16,viewFactory_UsersDemoComponent1);
    this._NgIf_16_6 = new import14.NgIf(this._appEl_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText(this._el_14,' Border\n      ',(null as any));
    this._text_18 = this.renderer.createText(this._el_1,'\n       ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_1,'button',(null as any));
    this.renderer.setElementAttribute(this._el_19,'class','btn');
    this._NgClass_19_3 = new import13.NgClass(this.parentInjector.get(import16.IterableDiffers),this.parentInjector.get(import17.KeyValueDiffers),new import8.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText(this._el_1,'\n    \n    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_1,'hr',(null as any));
    this._text_23 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._appEl_24 = new import2.AppElement(24,1,this,this._anchor_24);
    this._TemplateRef_24_5 = new import18.TemplateRef_(this._appEl_24,viewFactory_UsersDemoComponent2);
    this._NgFor_24_6 = new import15.NgFor(this._appEl_24.vcRef,this._TemplateRef_24_5,this.parentInjector.get(import16.IterableDiffers),this.ref);
    this._text_25 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_26 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._map_0 = import4.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'btn-warning': p0,
        'btn-success': p1
      }
      ;
    });
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_14,'click',this.eventHandler(this._handle_click_14_0.bind(this)));
    this._expr_6 = import7.UNINITIALIZED;
    this._map_1 = import4.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'btn-warning': p0,
        'btn-success': p1
      }
      ;
    });
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._expr_10 = import7.UNINITIALIZED;
    this._map_2 = import4.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'btn-warning': p0,
        'btn-success': p1
      }
      ;
    });
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._text_26
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.NgClass) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgClass_11_3; }
    if (((token === import18.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import14.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6; }
    if (((token === import13.NgClass) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NgClass_14_3; }
    if (((token === import13.NgClass) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._NgClass_19_3; }
    if (((token === import18.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import15.NgFor) && (24 === requestNodeIndex))) { return this._NgFor_24_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_2:any = 'btn';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgClass_11_3.klass = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._map_0(!this.context.isDetach,this.context.isDetach);
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._NgClass_11_3.ngClass = currVal_3;
      this._expr_3 = currVal_3;
    }
    if (!throwOnChange) { this._NgClass_11_3.ngDoCheck(); }
    const currVal_6:any = 'btn';
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._NgClass_14_3.klass = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._map_1(this.context.isBorder,!this.context.isBorder);
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgClass_14_3.ngClass = currVal_7;
      this._expr_7 = currVal_7;
    }
    if (!throwOnChange) { this._NgClass_14_3.ngDoCheck(); }
    const currVal_8:boolean = !this.context.isBorder;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgIf_16_6.ngIf = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_10:any = 'btn';
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgClass_19_3.klass = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._map_2(!this.context.isStart,this.context.isStart);
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgClass_19_3.ngClass = currVal_11;
      this._expr_11 = currVal_11;
    }
    if (!throwOnChange) { this._NgClass_19_3.ngDoCheck(); }
    changes = (null as any);
    const currVal_13:any = this.context.users;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._NgFor_24_6.ngForOf = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._NgFor_24_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_24_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_4:any = import4.interpolate(1,'\n        ',(this.context.isDetach? 'Reattach': 'Detach'),'\n    ');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_12,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_12:any = import4.interpolate(1,'\n        ',(this.context.isStart? 'Start': 'Stop'),'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setText(this._text_20,currVal_12);
      this._expr_12 = currVal_12;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.load(this._el_6.value)) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.isDetach = !this.context.isDetach)) !== false);
    return (true && pd_0);
  }
  private _handle_click_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.isBorder = !this.context.isBorder)) !== false);
    return (true && pd_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.isStart = !this.context.isStart)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_UsersDemoComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.UsersDemoComponent> {
  if ((renderType_UsersDemoComponent === (null as any))) { (renderType_UsersDemoComponent = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.Emulated,styles_UsersDemoComponent,{})); }
  return new _View_UsersDemoComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_UsersDemoComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UsersDemoComponent1,renderType_UsersDemoComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'No',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_UsersDemoComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UsersDemoComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_UsersDemoComponent2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UserComponent_0_4:import19.UserComponent;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UsersDemoComponent2,renderType_UsersDemoComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'user-profile',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import20.viewFactory_UserComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserComponent_0_4 = new import19.UserComponent(new import8.ElementRef(this._el_0),this.renderer,this.parent.parentInjector.get(import9.NgZone),compView_0.ref);
    this._appEl_0.initComponent(this._UserComponent_0_4,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_0.create(this._UserComponent_0_4,([] as any[]),(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.UserComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._UserComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._UserComponent_0_4.user = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this.parent.context.isDetach;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._UserComponent_0_4.isDetach = currVal_1;
      this._expr_1 = currVal_1;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UsersDemoComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UsersDemoComponent2(viewUtils,parentInjector,declarationEl);
}