/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/demos/detach/user.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/linker/element_ref';
import * as import9 from '@angular/core/src/zone/ng_zone';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/common/src/directives/ng_for';
import * as import13 from '@angular/common/src/pipes/json_pipe';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import16 from '@angular/core/src/security';
var renderType_UserComponent_Host:import0.RenderComponentType = (null as any);
class _View_UserComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _UserComponent_0_4:import3.UserComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserComponent_Host0,renderType_UserComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('user-profile',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_UserComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._UserComponent_0_4 = new import3.UserComponent(new import8.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import9.NgZone),compView_0.ref);
    this._appEl_0.initComponent(this._UserComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._UserComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.UserComponent) && (0 === requestNodeIndex))) { return this._UserComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_UserComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_UserComponent_Host === (null as any))) { (renderType_UserComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_UserComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const UserComponentNgFactory:import11.ComponentFactory<import3.UserComponent> = new import11.ComponentFactory<import3.UserComponent>('user-profile',viewFactory_UserComponent_Host0,import3.UserComponent);
const styles_UserComponent:any[] = ['[_nghost-%COMP%]{\n            display: block;\n        }\n        .media[_ngcontent-%COMP%]{\n            margin: 5px 0;\n            padding:3px;\n        }\n        .dp[_ngcontent-%COMP%]{\n            border:10px solid #eee;\n            transition: all 0.2s ease-in-out;\n        }\n        .dp[_ngcontent-%COMP%]:hover{\n            border:2px solid #eee;\n            transform:rotate(360deg);\n            -ms-transform:rotate(360deg);\n            -webkit-transform:rotate(360deg);\n            \n        }'];
var renderType_UserComponent:import0.RenderComponentType = (null as any);
class _View_UserComponent0 extends import1.AppView<import3.UserComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import2.AppElement;
  _TemplateRef_24_5:any;
  _NgFor_24_6:import12.NgFor;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  _pipe_json_0:import13.JsonPipe;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserComponent0,renderType_UserComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n        ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','row');
    this._text_2 = this.renderer.createText(this._el_1,'\n            ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','col-lg-5');
    this._text_4 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','media');
    this._text_6 = this.renderer.createText(this._el_5,'\n                    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'a',(null as any));
    this.renderer.setElementAttribute(this._el_7,'class','pull-left');
    this.renderer.setElementAttribute(this._el_7,'href','#');
    this._text_8 = this.renderer.createText(this._el_7,'\n                        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'img',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','media-object dp img-circle');
    this.renderer.setElementAttribute(this._el_9,'style','width: 100px;height:100px;');
    this._text_10 = this.renderer.createText(this._el_7,'\n                    ',(null as any));
    this._text_11 = this.renderer.createText(this._el_5,'\n                    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','media-body');
    this._text_13 = this.renderer.createText(this._el_12,'\n                        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','media-heading');
    this._text_15 = this.renderer.createText(this._el_14,'',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'small',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_12,'\n                        ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_12,'h5',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText(this._el_12,'\n                        ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_12,'hr',(null as any));
    this.renderer.setElementAttribute(this._el_22,'style','margin:8px auto');
    this._text_23 = this.renderer.createText(this._el_12,'\n        \n                        ',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_12,(null as any));
    this._appEl_24 = new import2.AppElement(24,12,this,this._anchor_24);
    this._TemplateRef_24_5 = new import14.TemplateRef_(this._appEl_24,viewFactory_UserComponent1);
    this._NgFor_24_6 = new import12.NgFor(this._appEl_24.vcRef,this._TemplateRef_24_5,this.parentInjector.get(import15.IterableDiffers),this.ref);
    this._text_25 = this.renderer.createText(this._el_12,'                        \n                    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_5,'\n                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_3,'\n                ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_3,'pre',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'',(null as any));
    this._text_30 = this.renderer.createText(this._el_3,'\n            ',(null as any));
    this._text_31 = this.renderer.createText(this._el_1,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._pipe_json_0 = new import13.JsonPipe();
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import12.NgFor) && (24 === requestNodeIndex))) { return this._NgFor_24_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const valUnwrapper:any = new import7.ValueUnwrapper();
    changes = (null as any);
    const currVal_4:any = this.context.tags;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._NgFor_24_6.ngForOf = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._NgFor_24_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_24_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.context.user.picture.thumbnail;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_9,'src',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(3,'',this.context.user.name.title,' ',this.context.user.name.first,' ',this.context.user.name.last,' ');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_15,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,' ',this.context.user.location.state,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_17,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(2,'Phone: ',this.context.user.phone,', Mobile: ',this.context.user.cell,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_20,currVal_3);
      this._expr_3 = currVal_3;
    }
    valUnwrapper.reset();
    const currVal_5:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_json_0.transform(this.context.user)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_5,currVal_5))) {
      this.renderer.setText(this._text_29,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_UserComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.UserComponent> {
  if ((renderType_UserComponent === (null as any))) { (renderType_UserComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_UserComponent,{})); }
  return new _View_UserComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_UserComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_UserComponent1,renderType_UserComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','label');
    this.renderer.setElementAttribute(this._el_0,'style','margin-right: 5px;');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = ((this.context.index % 3) != 0);
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'label-default',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = ((this.context.index % 3) == 0);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'label-info',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'\n                            ',this.context.$implicit,'\n                        ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_UserComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_UserComponent1(viewUtils,parentInjector,declarationEl);
}