/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../../../../app/demos/board/board.demo.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view_utils';
import * as import4 from '@angular/core/src/metadata/view';
import * as import5 from '@angular/core/src/linker/view_type';
import * as import6 from '@angular/core/src/change_detection/constants';
import * as import7 from '@angular/core/src/linker/component_factory';
import * as import8 from '@angular/core/src/linker/element_ref';
import * as import9 from '@angular/core/src/zone/ng_zone';
import * as import10 from '@angular/core/src/application_ref';
import * as import11 from '@angular/core/src/linker/view_container';
import * as import12 from '../../../../app/demos/counter/counter.component';
import * as import13 from '../counter/counter.component.ngfactory';
import * as import14 from '../../../node_modules/@angular/common/src/directives/ng_class.ngfactory';
import * as import15 from '../../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import16 from '../../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import17 from '@angular/common/src/pipes/number_pipe';
import * as import18 from '@angular/core/src/change_detection/change_detection_util';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import20 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import21 from '@angular/core/src/linker/template_ref';
import * as import22 from '@angular/core/src/i18n/tokens';
import * as import23 from '@angular/common/src/directives/ng_if';
import * as import24 from '@angular/common/src/directives/ng_class';
import * as import25 from '@angular/common/src/directives/ng_for';
export class Wrapper_BoardDemoComponent {
  /*private*/ _eventHandler:Function;
  context:import0.BoardDemoComponent;
  /*private*/ _changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this._changed = false;
    this.context = new import0.BoardDemoComponent(p0,p1,p2,p3,p4);
  }
  ngOnDetach(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any):void {
  }
  ngOnDestroy():void {
  }
  ngDoCheck(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this._changed;
    this._changed = false;
    if (!throwOnChange) { this.context.ngDoCheck(); }
    return changed;
  }
  checkHost(view:import1.AppView<any>,componentView:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
  handleEvent(eventName:string,$event:any):boolean {
    var result:boolean = true;
    return result;
  }
  subscribe(view:import1.AppView<any>,_eventHandler:any):void {
    this._eventHandler = _eventHandler;
  }
}
var renderType_BoardDemoComponent_Host:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.None,([] as any[]),{});
class View_BoardDemoComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import0.BoardDemoComponent>;
  _BoardDemoComponent_0_3:Wrapper_BoardDemoComponent;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_BoardDemoComponent_Host0,renderType_BoardDemoComponent_Host,import5.ViewType.HOST,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.selectOrCreateRenderHostElement(this.renderer,'ng-component',import3.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this.compView_0 = new View_BoardDemoComponent0(this.viewUtils,this,0,this._el_0);
    this._BoardDemoComponent_0_3 = new Wrapper_BoardDemoComponent(new import8.ElementRef(this._el_0),this.renderer,this.injectorGet(import9.NgZone,this.parentIndex),this.compView_0.ref,this.injectorGet(import10.ApplicationRef,this.parentIndex));
    this.compView_0.create(this._BoardDemoComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [this._el_0]),(null as any));
    return new import7.ComponentRef_<any>(0,this,this._el_0,this._BoardDemoComponent_0_3.context);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.BoardDemoComponent) && (0 === requestNodeIndex))) { return this._BoardDemoComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._BoardDemoComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
export const BoardDemoComponentNgFactory:import7.ComponentFactory<import0.BoardDemoComponent> = new import7.ComponentFactory<import0.BoardDemoComponent>('ng-component',View_BoardDemoComponent_Host0,import0.BoardDemoComponent);
const styles_BoardDemoComponent:any[] = ['[_nghost-%COMP%]{ display: block; }\n        .flow[_ngcontent-%COMP%]{\n            float:left;\n        }'];
class View_BoardDemoComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_BoardDemoComponent1,renderType_BoardDemoComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'No',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_BoardDemoComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_BoardDemoComponent2,renderType_BoardDemoComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'No',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_BoardDemoComponent3 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_BoardDemoComponent3,renderType_BoardDemoComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'No',(null as any));
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
class View_BoardDemoComponent4 extends import1.AppView<any> {
  _el_0:any;
  compView_0:import1.AppView<import12.CounterComponent>;
  _CounterComponent_0_3:import13.Wrapper_CounterComponent;
  _text_1:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any,declaredViewContainer:import11.ViewContainer) {
    super(View_BoardDemoComponent4,renderType_BoardDemoComponent,import5.ViewType.EMBEDDED,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways,declaredViewContainer);
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    this._el_0 = import3.createRenderElement(this.renderer,(null as any),'counter',new import3.InlineArray2(2,'class','flow'),(null as any));
    this.compView_0 = new import13.View_CounterComponent0(this.viewUtils,this,0,this._el_0);
    this._CounterComponent_0_3 = new import13.Wrapper_CounterComponent(new import8.ElementRef(this._el_0),this.renderer,this.parentView.parentView.injectorGet(import9.NgZone,this.parentView.parentIndex),this.compView_0.ref,this.parentView.parentView.injectorGet(import10.ApplicationRef,this.parentView.parentIndex));
    this._text_1 = this.renderer.createText((null as any),'    \n      ',(null as any));
    this.compView_0.create(this._CounterComponent_0_3.context);
    this.init(this._el_0,((<any>this.renderer).directRenderer? (null as any): [
      this._el_0,
      this._text_1
    ]
    ),(null as any));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.CounterComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._CounterComponent_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0_0_0:any = this.parentView.context.isDetectChanges;
    this._CounterComponent_0_3.check_isDetectChanges(currVal_0_0_0,throwOnChange,false);
    const currVal_0_0_1:any = 0;
    this._CounterComponent_0_3.check_value(currVal_0_0_1,throwOnChange,false);
    const currVal_0_0_2:any = 10;
    this._CounterComponent_0_3.check_ms(currVal_0_0_2,throwOnChange,false);
    const currVal_0_0_3:any = this.parentView.context.isTick;
    this._CounterComponent_0_3.check_isTick(currVal_0_0_3,throwOnChange,false);
    this._CounterComponent_0_3.ngDoCheck(this,this._el_0,throwOnChange);
    this.compView_0.internalDetectChanges(throwOnChange);
  }
  destroyInternal():void {
    this.compView_0.destroy();
    this._CounterComponent_0_3.ngOnDestroy();
  }
  visitRootNodesInternal(cb:any,ctx:any):void {
    cb(this._el_0,ctx);
  }
}
var renderType_BoardDemoComponent:import2.RenderComponentType = import3.createRenderComponentType('',0,import4.ViewEncapsulation.Emulated,styles_BoardDemoComponent,{});
export class View_BoardDemoComponent0 extends import1.AppView<import0.BoardDemoComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _NgClass_9_3:import14.Wrapper_NgClass;
  _text_10:any;
  _anchor_11:any;
  /*private*/ _vc_11:import11.ViewContainer;
  _TemplateRef_11_5:any;
  _NgIf_11_6:import15.Wrapper_NgIf;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _NgClass_14_3:import14.Wrapper_NgClass;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _vc_16:import11.ViewContainer;
  _TemplateRef_16_5:any;
  _NgIf_16_6:import15.Wrapper_NgIf;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _NgClass_19_3:import14.Wrapper_NgClass;
  _text_20:any;
  _anchor_21:any;
  /*private*/ _vc_21:import11.ViewContainer;
  _TemplateRef_21_5:any;
  _NgIf_21_6:import15.Wrapper_NgIf;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _el_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _anchor_53:any;
  /*private*/ _vc_53:import11.ViewContainer;
  _TemplateRef_53_5:any;
  _NgFor_53_6:import16.Wrapper_NgFor;
  _text_54:any;
  _text_55:any;
  _map_71:any;
  _map_72:any;
  _map_73:any;
  /*private*/ _expr_74:any;
  _pipe_number_0:import17.DecimalPipe;
  _pipe_number_0_0:any;
  constructor(viewUtils:import3.ViewUtils,parentView:import1.AppView<any>,parentIndex:number,parentElement:any) {
    super(View_BoardDemoComponent0,renderType_BoardDemoComponent,import5.ViewType.COMPONENT,viewUtils,parentView,parentIndex,parentElement,import6.ChangeDetectorStatus.CheckAlways);
    this._map_71 = import3.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'btn-warning': p0,
        'btn-success': p1
      }
      ;
    });
    this._map_72 = import3.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'btn-warning': p0,
        'btn-success': p1
      }
      ;
    });
    this._map_73 = import3.pureProxy2((p0:any,p1:any):{[key: string]:any} => {
      return {
        'btn-warning': p0,
        'btn-success': p1
      }
      ;
    });
    this._expr_74 = import18.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import7.ComponentRef<any> {
    const parentRenderNode:any = this.renderer.createViewRoot(this.parentElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = import3.createRenderElement(this.renderer,parentRenderNode,'div',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = import3.createRenderElement(this.renderer,this._el_1,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'Counters components',(null as any));
    this._text_5 = this.renderer.createText(this._el_1,'    \n    ',(null as any));
    this._el_6 = import3.createRenderElement(this.renderer,this._el_1,'P',new import3.InlineArray2(2,'class','desc'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n        This demo shows how we can stop the tick that setTimout causes by using NgZone class \n        and how to update the component area with ChangeDetectorRef class.  \n    ',(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n      \n      ',(null as any));
    this._el_9 = import3.createRenderElement(this.renderer,this._el_1,'button',new import3.InlineArray2(2,'class','btn'),(null as any));
    this._NgClass_9_3 = new import14.Wrapper_NgClass(this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import20.KeyValueDiffers,this.parentIndex),new import8.ElementRef(this._el_9),this.renderer);
    this._text_10 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._anchor_11 = this.renderer.createTemplateAnchor(this._el_9,(null as any));
    this._vc_11 = new import11.ViewContainer(11,9,this,this._anchor_11);
    this._TemplateRef_11_5 = new import21.TemplateRef_(this,11,this._anchor_11);
    this._NgIf_11_6 = new import15.Wrapper_NgIf(this._vc_11.vcRef,this._TemplateRef_11_5);
    this._text_12 = this.renderer.createText(this._el_9,'Ticks\n      ',(null as any));
    this._text_13 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_14 = import3.createRenderElement(this.renderer,this._el_1,'button',new import3.InlineArray2(2,'class','btn'),(null as any));
    this._NgClass_14_3 = new import14.Wrapper_NgClass(this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import20.KeyValueDiffers,this.parentIndex),new import8.ElementRef(this._el_14),this.renderer);
    this._text_15 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._vc_16 = new import11.ViewContainer(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import21.TemplateRef_(this,16,this._anchor_16);
    this._NgIf_16_6 = new import15.Wrapper_NgIf(this._vc_16.vcRef,this._TemplateRef_16_5);
    this._text_17 = this.renderer.createText(this._el_14,' Detect Changes\n      ',(null as any));
    this._text_18 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_19 = import3.createRenderElement(this.renderer,this._el_1,'button',new import3.InlineArray2(2,'class','btn'),(null as any));
    this._NgClass_19_3 = new import14.Wrapper_NgClass(this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.parentView.injectorGet(import20.KeyValueDiffers,this.parentIndex),new import8.ElementRef(this._el_19),this.renderer);
    this._text_20 = this.renderer.createText(this._el_19,'\n       ',(null as any));
    this._anchor_21 = this.renderer.createTemplateAnchor(this._el_19,(null as any));
    this._vc_21 = new import11.ViewContainer(21,19,this,this._anchor_21);
    this._TemplateRef_21_5 = new import21.TemplateRef_(this,21,this._anchor_21);
    this._NgIf_21_6 = new import15.Wrapper_NgIf(this._vc_21.vcRef,this._TemplateRef_21_5);
    this._text_22 = this.renderer.createText(this._el_19,' Border\n      ',(null as any));
    this._text_23 = this.renderer.createText(this._el_1,'      \n      ',(null as any));
    this._el_24 = import3.createRenderElement(this.renderer,this._el_1,'br',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_25 = this.renderer.createText(this._el_1,'    \n      ',(null as any));
    this._el_26 = import3.createRenderElement(this.renderer,this._el_1,'h4',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._el_27 = import3.createRenderElement(this.renderer,this._el_26,'span',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'',(null as any));
    this._text_29 = this.renderer.createText(this._el_1,'\n       Change to size: \n        ',(null as any));
    this._el_30 = import3.createRenderElement(this.renderer,this._el_1,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'1',(null as any));
    this._text_32 = this.renderer.createText(this._el_1,' |\n        ',(null as any));
    this._el_33 = import3.createRenderElement(this.renderer,this._el_1,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'100',(null as any));
    this._text_35 = this.renderer.createText(this._el_1,' |\n        ',(null as any));
    this._el_36 = import3.createRenderElement(this.renderer,this._el_1,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'500',(null as any));
    this._text_38 = this.renderer.createText(this._el_1,' |\n        ',(null as any));
    this._el_39 = import3.createRenderElement(this.renderer,this._el_1,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'1,000',(null as any));
    this._text_41 = this.renderer.createText(this._el_1,' |\n        ',(null as any));
    this._el_42 = import3.createRenderElement(this.renderer,this._el_1,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'1,500',(null as any));
    this._text_44 = this.renderer.createText(this._el_1,' |\n        ',(null as any));
    this._el_45 = import3.createRenderElement(this.renderer,this._el_1,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'3,000',(null as any));
    this._text_47 = this.renderer.createText(this._el_1,' |\n        ',(null as any));
    this._el_48 = import3.createRenderElement(this.renderer,this._el_1,'a',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'5,500',(null as any));
    this._text_50 = this.renderer.createText(this._el_1,' |\n        \n      ',(null as any));
    this._el_51 = import3.createRenderElement(this.renderer,this._el_1,'hr',import3.EMPTY_INLINE_ARRAY,(null as any));
    this._text_52 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._anchor_53 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._vc_53 = new import11.ViewContainer(53,1,this,this._anchor_53);
    this._TemplateRef_53_5 = new import21.TemplateRef_(this,53,this._anchor_53);
    this._NgFor_53_6 = new import16.Wrapper_NgFor(this._vc_53.vcRef,this._TemplateRef_53_5,this.parentView.injectorGet(import19.IterableDiffers,this.parentIndex),this.ref);
    this._text_54 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_55 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = import3.subscribeToRenderElement(this,this._el_9,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_9));
    var disposable_1:Function = import3.subscribeToRenderElement(this,this._el_14,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_14));
    var disposable_2:Function = import3.subscribeToRenderElement(this,this._el_19,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_19));
    this._pipe_number_0 = new import17.DecimalPipe(this.parentView.injectorGet(import22.LOCALE_ID,this.parentIndex));
    this._pipe_number_0_0 = import3.pureProxy1(this._pipe_number_0.transform.bind(this._pipe_number_0));
    var disposable_3:Function = import3.subscribeToRenderElement(this,this._el_30,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_30));
    var disposable_4:Function = import3.subscribeToRenderElement(this,this._el_33,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_33));
    var disposable_5:Function = import3.subscribeToRenderElement(this,this._el_36,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_36));
    var disposable_6:Function = import3.subscribeToRenderElement(this,this._el_39,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_39));
    var disposable_7:Function = import3.subscribeToRenderElement(this,this._el_42,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_42));
    var disposable_8:Function = import3.subscribeToRenderElement(this,this._el_45,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_45));
    var disposable_9:Function = import3.subscribeToRenderElement(this,this._el_48,new import3.InlineArray2(2,'click',(null as any)),this.eventHandler(this.handleEvent_48));
    this.init((null as any),((<any>this.renderer).directRenderer? (null as any): [
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._anchor_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._anchor_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._anchor_53,
      this._text_54,
      this._text_55
    ]
    ),[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import21.TemplateRef) && (11 === requestNodeIndex))) { return this._TemplateRef_11_5; }
    if (((token === import23.NgIf) && (11 === requestNodeIndex))) { return this._NgIf_11_6.context; }
    if (((token === import24.NgClass) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgClass_9_3.context; }
    if (((token === import21.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import23.NgIf) && (16 === requestNodeIndex))) { return this._NgIf_16_6.context; }
    if (((token === import24.NgClass) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._NgClass_14_3.context; }
    if (((token === import21.TemplateRef) && (21 === requestNodeIndex))) { return this._TemplateRef_21_5; }
    if (((token === import23.NgIf) && (21 === requestNodeIndex))) { return this._NgIf_21_6.context; }
    if (((token === import24.NgClass) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._NgClass_19_3.context; }
    if (((token === import21.TemplateRef) && (53 === requestNodeIndex))) { return this._TemplateRef_53_5; }
    if (((token === import25.NgFor) && (53 === requestNodeIndex))) { return this._NgFor_53_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import18.ValueUnwrapper();
    const currVal_9_0_0:any = 'btn';
    this._NgClass_9_3.check_klass(currVal_9_0_0,throwOnChange,false);
    const currVal_9_0_1:any = this._map_71(this.context.isTick,!this.context.isTick);
    this._NgClass_9_3.check_ngClass(currVal_9_0_1,throwOnChange,false);
    this._NgClass_9_3.ngDoCheck(this,this._el_9,throwOnChange);
    const currVal_11_0_0:boolean = !this.context.isTick;
    this._NgIf_11_6.check_ngIf(currVal_11_0_0,throwOnChange,false);
    this._NgIf_11_6.ngDoCheck(this,this._anchor_11,throwOnChange);
    const currVal_14_0_0:any = 'btn';
    this._NgClass_14_3.check_klass(currVal_14_0_0,throwOnChange,false);
    const currVal_14_0_1:any = this._map_72(!this.context.isDetectChanges,this.context.isDetectChanges);
    this._NgClass_14_3.check_ngClass(currVal_14_0_1,throwOnChange,false);
    this._NgClass_14_3.ngDoCheck(this,this._el_14,throwOnChange);
    const currVal_16_0_0:boolean = !this.context.isDetectChanges;
    this._NgIf_16_6.check_ngIf(currVal_16_0_0,throwOnChange,false);
    this._NgIf_16_6.ngDoCheck(this,this._anchor_16,throwOnChange);
    const currVal_19_0_0:any = 'btn';
    this._NgClass_19_3.check_klass(currVal_19_0_0,throwOnChange,false);
    const currVal_19_0_1:any = this._map_73(this.context.isBorder,!this.context.isBorder);
    this._NgClass_19_3.check_ngClass(currVal_19_0_1,throwOnChange,false);
    this._NgClass_19_3.ngDoCheck(this,this._el_19,throwOnChange);
    const currVal_21_0_0:boolean = !this.context.isBorder;
    this._NgIf_21_6.check_ngIf(currVal_21_0_0,throwOnChange,false);
    this._NgIf_21_6.ngDoCheck(this,this._anchor_21,throwOnChange);
    const currVal_53_0_0:any = this.context.counters;
    this._NgFor_53_6.check_ngForOf(currVal_53_0_0,throwOnChange,false);
    this._NgFor_53_6.ngDoCheck(this,this._anchor_53,throwOnChange);
    this._vc_11.detectChangesInNestedViews(throwOnChange);
    this._vc_16.detectChangesInNestedViews(throwOnChange);
    this._vc_21.detectChangesInNestedViews(throwOnChange);
    this._vc_53.detectChangesInNestedViews(throwOnChange);
    valUnwrapper.reset();
    const currVal_74:any = import3.inlineInterpolate(1,'Size: ',valUnwrapper.unwrap(import3.castByValue(this._pipe_number_0_0,this._pipe_number_0.transform)(this.context.counters.length)),'');
    if ((valUnwrapper.hasWrappedValue || import3.checkBinding(throwOnChange,this._expr_74,currVal_74))) {
      this.renderer.setText(this._text_28,currVal_74);
      this._expr_74 = currVal_74;
    }
  }
  destroyInternal():void {
    this._vc_11.destroyNestedViews();
    this._vc_16.destroyNestedViews();
    this._vc_21.destroyNestedViews();
    this._vc_53.destroyNestedViews();
  }
  createEmbeddedViewInternal(nodeIndex:number):import1.AppView<any> {
    if ((nodeIndex == 11)) { return new View_BoardDemoComponent1(this.viewUtils,this,11,this._anchor_11,this._vc_11); }
    if ((nodeIndex == 16)) { return new View_BoardDemoComponent2(this.viewUtils,this,16,this._anchor_16,this._vc_16); }
    if ((nodeIndex == 21)) { return new View_BoardDemoComponent3(this.viewUtils,this,21,this._anchor_21,this._vc_21); }
    if ((nodeIndex == 53)) { return new View_BoardDemoComponent4(this.viewUtils,this,53,this._anchor_53,this._vc_53); }
    return (null as any);
  }
  handleEvent_9(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.isTick = !this.context.isTick)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_14(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.isDetectChanges = !this.context.isDetectChanges)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_19(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>(this.context.isBorder = !this.context.isBorder)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_30(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.addCounter(1)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_33(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.addCounter(100)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_36(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.addCounter(500)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_39(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.addCounter(1000)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_42(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.addCounter(1500)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_45(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.addCounter(3000)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
  handleEvent_48(eventName:string,$event:any):boolean {
    this.markPathToRootAsCheckOnce();
    var result:boolean = true;
    if ((eventName == 'click')) {
      const pd_sub_0:any = ((<any>this.context.addCounter(5000)) !== false);
      result = (pd_sub_0 && result);
    }
    return result;
  }
}