/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../../app/demos/board/counter2.component';
const styles_Counter2Component:any[] = ['[_nghost-%COMP%]{\n                display: block;\n                width: 50px; height: 50px;\n                border: 1px dotted black;\n                text-align: center;\n                vertical-align: middle;\n                margin: 8px;\n                            \n        }'];
export const RenderType_Counter2Component:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_Counter2Component,
  data: {}
}
);
export function View_Counter2Component_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.Counter2Component = v.component;
    const currVal_0:any = co.value;
    ck(v,2,0,currVal_0);
  });
}
function View_Counter2Component_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'counter2',([] as any[]),(null as any),(null as any),(null as any),View_Counter2Component_0,RenderType_Counter2Component)),
    import0.ɵdid(155648,(null as any),0,import1.Counter2Component,[
      import0.ElementRef,
      import0.Renderer2,
      import0.NgZone,
      import0.ChangeDetectorRef,
      import0.ApplicationRef
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const Counter2ComponentNgFactory:import0.ComponentFactory<import1.Counter2Component> = import0.ɵccf('counter2',import1.Counter2Component,View_Counter2Component_Host_0,{value: 'value'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvRXlhbC9EZXNrdG9wL1BlcmZvcm1hbmNlIE9wdGltaXphdGlvbi9uZy1jb3Vyc2UoY2QpL2FwcC9kZW1vcy9ib2FyZC9jb3VudGVyMi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvRXlhbC9EZXNrdG9wL1BlcmZvcm1hbmNlIE9wdGltaXphdGlvbi9uZy1jb3Vyc2UoY2QpL2FwcC9kZW1vcy9ib2FyZC9jb3VudGVyMi5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9FeWFsL0Rlc2t0b3AvUGVyZm9ybWFuY2UgT3B0aW1pemF0aW9uL25nLWNvdXJzZShjZCkvYXBwL2RlbW9zL2JvYXJkL2NvdW50ZXIyLmNvbXBvbmVudC50cy5Db3VudGVyMkNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvRXlhbC9EZXNrdG9wL1BlcmZvcm1hbmNlIE9wdGltaXphdGlvbi9uZy1jb3Vyc2UoY2QpL2FwcC9kZW1vcy9ib2FyZC9jb3VudGVyMi5jb21wb25lbnQudHMuQ291bnRlcjJDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8ZGl2Pnt7dmFsdWV9fTwvZGl2PlxuIiwiPGNvdW50ZXIyPjwvY291bnRlcjI+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO0lBQ0k7SUFBSztNQUFBO01BQUE7SUFBQTtJQUFBO0lBQWU7Ozs7SUFBZjtJQUFBOzs7OztJQ0RUO2dCQUFBOzs7Ozs7SUFBQTtLQUFBOzs7SUFBQTs7OyJ9
