/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../app/demos/accordion/demo.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
import * as import10 from '../../../../app/demos/accordion/accordion.component';
import * as import11 from '../../../../app/demos/accordion/item.component';
import * as import12 from '../../../../app/demos/accordion/item-no-tick.component';
import * as import13 from './accordion.component.ngfactory';
import * as import14 from '@angular/core/src/linker/element_ref';
import * as import15 from '@angular/core/src/zone/ng_zone';
import * as import16 from '@angular/core/src/application_ref';
import * as import17 from './item.component.ngfactory';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from './item-no-tick.component.ngfactory';
var renderType_AccordionDemoComponent_Host:import0.RenderComponentType = (null as any);
class _View_AccordionDemoComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _AccordionDemoComponent_0_4:import3.AccordionDemoComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AccordionDemoComponent_Host0,renderType_AccordionDemoComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AccordionDemoComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AccordionDemoComponent_0_4 = new import3.AccordionDemoComponent();
    this._appEl_0.initComponent(this._AccordionDemoComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._AccordionDemoComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.AccordionDemoComponent) && (0 === requestNodeIndex))) { return this._AccordionDemoComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_AccordionDemoComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_AccordionDemoComponent_Host === (null as any))) { (renderType_AccordionDemoComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AccordionDemoComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AccordionDemoComponentNgFactory:import9.ComponentFactory<import3.AccordionDemoComponent> = new import9.ComponentFactory<import3.AccordionDemoComponent>('ng-component',viewFactory_AccordionDemoComponent_Host0,import3.AccordionDemoComponent);
const styles_AccordionDemoComponent:any[] = ([] as any[]);
var renderType_AccordionDemoComponent:import0.RenderComponentType = (null as any);
class _View_AccordionDemoComponent0 extends import1.AppView<import3.AccordionDemoComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  /*private*/ _appEl_6:import2.AppElement;
  _AccordionComponent_6_4:import10.AccordionComponent;
  _text_7:any;
  _el_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _ItemComponent_8_4:import11.ItemComponent;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _appEl_10:import2.AppElement;
  _TemplateRef_10_4:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import2.AppElement;
  _ItemComponent_13_4:import11.ItemComponent;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _ItemComponent_16_4:import11.ItemComponent;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import2.AppElement;
  _AccordionComponent_26_4:import10.AccordionComponent;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import2.AppElement;
  _Item2Component_28_4:import12.Item2Component;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import2.AppElement;
  _Item2Component_31_4:import12.Item2Component;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import2.AppElement;
  _Item2Component_34_4:import12.Item2Component;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AccordionDemoComponent0,renderType_AccordionDemoComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'h4',(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'(click) in the template cause a tick',(null as any));
    this._text_5 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_1,'accordion',(null as any));
    this._appEl_6 = new import2.AppElement(6,1,this,this._el_6);
    var compView_6:any = import13.viewFactory_AccordionComponent0(this.viewUtils,this.injector(6),this._appEl_6);
    this._AccordionComponent_6_4 = new import10.AccordionComponent(new import14.ElementRef(this._el_6),this.renderer,this.parentInjector.get(import15.NgZone),compView_6.ref,this.parentInjector.get(import16.ApplicationRef));
    this._appEl_6.initComponent(this._AccordionComponent_6_4,([] as any[]),compView_6);
    this._text_7 = this.renderer.createText((null as any),'        \n        ',(null as any));
    this._el_8 = this.renderer.createElement((null as any),'item',(null as any));
    this.renderer.setElementAttribute(this._el_8,'title','title 1');
    this._appEl_8 = new import2.AppElement(8,6,this,this._el_8);
    var compView_8:any = import17.viewFactory_ItemComponent0(this.viewUtils,this.injector(8),this._appEl_8);
    this._ItemComponent_8_4 = new import11.ItemComponent(new import14.ElementRef(this._el_8),this.renderer,this.parentInjector.get(import15.NgZone),compView_8.ref,this.parentInjector.get(import16.ApplicationRef));
    this._appEl_8.initComponent(this._ItemComponent_8_4,([] as any[]),compView_8);
    this._text_9 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._anchor_10 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_10 = new import2.AppElement(10,8,this,this._anchor_10);
    this._TemplateRef_10_4 = new import18.TemplateRef_(this._appEl_10,viewFactory_AccordionDemoComponent1);
    this._text_11 = this.renderer.createText((null as any),'\n            desc 1\n        ',(null as any));
      compView_8.create(this._ItemComponent_8_4,[([] as any[]).concat([
        this._text_9,
        this._anchor_10,
        this._text_11
      ]
    )],(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'item',(null as any));
    this.renderer.setElementAttribute(this._el_13,'title','title 2');
    this._appEl_13 = new import2.AppElement(13,6,this,this._el_13);
    var compView_13:any = import17.viewFactory_ItemComponent0(this.viewUtils,this.injector(13),this._appEl_13);
    this._ItemComponent_13_4 = new import11.ItemComponent(new import14.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import15.NgZone),compView_13.ref,this.parentInjector.get(import16.ApplicationRef));
    this._appEl_13.initComponent(this._ItemComponent_13_4,([] as any[]),compView_13);
    this._text_14 = this.renderer.createText((null as any),'desc 2',(null as any));
    compView_13.create(this._ItemComponent_13_4,[([] as any[]).concat([this._text_14])],(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'item',(null as any));
    this.renderer.setElementAttribute(this._el_16,'title','title 3');
    this._appEl_16 = new import2.AppElement(16,6,this,this._el_16);
    var compView_16:any = import17.viewFactory_ItemComponent0(this.viewUtils,this.injector(16),this._appEl_16);
    this._ItemComponent_16_4 = new import11.ItemComponent(new import14.ElementRef(this._el_16),this.renderer,this.parentInjector.get(import15.NgZone),compView_16.ref,this.parentInjector.get(import16.ApplicationRef));
    this._appEl_16.initComponent(this._ItemComponent_16_4,([] as any[]),compView_16);
    this._text_17 = this.renderer.createText((null as any),'desc 3',(null as any));
    compView_16.create(this._ItemComponent_16_4,[([] as any[]).concat([this._text_17])],(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_6.create(this._AccordionComponent_6_4,[([] as any[]).concat([
        this._text_7,
        this._el_8,
        this._text_12,
        this._el_13,
        this._text_15,
        this._el_16,
        this._text_18
      ]
    )],(null as any));
    this._text_19 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_1,'h4',(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'No ticks (NgZone)',(null as any));
    this._text_22 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_1,'p',(null as any));
    this._text_24 = this.renderer.createText(this._el_23,'\n        This demo shows how we can stop the tick that happens because a click event. \n        In this approach we can\'t register an event in the template because we need\n        to use the NgZone class.\n    ',(null as any));
    this._text_25 = this.renderer.createText(this._el_1,' \n    ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_1,'accordion',(null as any));
    this._appEl_26 = new import2.AppElement(26,1,this,this._el_26);
    var compView_26:any = import13.viewFactory_AccordionComponent0(this.viewUtils,this.injector(26),this._appEl_26);
    this._AccordionComponent_26_4 = new import10.AccordionComponent(new import14.ElementRef(this._el_26),this.renderer,this.parentInjector.get(import15.NgZone),compView_26.ref,this.parentInjector.get(import16.ApplicationRef));
    this._appEl_26.initComponent(this._AccordionComponent_26_4,([] as any[]),compView_26);
    this._text_27 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'item2',(null as any));
    this.renderer.setElementAttribute(this._el_28,'title','title 1');
    this._appEl_28 = new import2.AppElement(28,26,this,this._el_28);
    var compView_28:any = import19.viewFactory_Item2Component0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Item2Component_28_4 = new import12.Item2Component(new import14.ElementRef(this._el_28),this.renderer,this.parentInjector.get(import15.NgZone),compView_28.ref,this.parentInjector.get(import16.ApplicationRef));
    this._appEl_28.initComponent(this._Item2Component_28_4,([] as any[]),compView_28);
    this._text_29 = this.renderer.createText((null as any),'desc 1',(null as any));
    compView_28.create(this._Item2Component_28_4,[([] as any[]).concat([this._text_29])],(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'item2',(null as any));
    this.renderer.setElementAttribute(this._el_31,'title','title 2');
    this._appEl_31 = new import2.AppElement(31,26,this,this._el_31);
    var compView_31:any = import19.viewFactory_Item2Component0(this.viewUtils,this.injector(31),this._appEl_31);
    this._Item2Component_31_4 = new import12.Item2Component(new import14.ElementRef(this._el_31),this.renderer,this.parentInjector.get(import15.NgZone),compView_31.ref,this.parentInjector.get(import16.ApplicationRef));
    this._appEl_31.initComponent(this._Item2Component_31_4,([] as any[]),compView_31);
    this._text_32 = this.renderer.createText((null as any),'desc 2',(null as any));
    compView_31.create(this._Item2Component_31_4,[([] as any[]).concat([this._text_32])],(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'item2',(null as any));
    this.renderer.setElementAttribute(this._el_34,'title','title 3');
    this._appEl_34 = new import2.AppElement(34,26,this,this._el_34);
    var compView_34:any = import19.viewFactory_Item2Component0(this.viewUtils,this.injector(34),this._appEl_34);
    this._Item2Component_34_4 = new import12.Item2Component(new import14.ElementRef(this._el_34),this.renderer,this.parentInjector.get(import15.NgZone),compView_34.ref,this.parentInjector.get(import16.ApplicationRef));
    this._appEl_34.initComponent(this._Item2Component_34_4,([] as any[]),compView_34);
    this._text_35 = this.renderer.createText((null as any),'desc 3',(null as any));
    compView_34.create(this._Item2Component_34_4,[([] as any[]).concat([this._text_35])],(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_26.create(this._AccordionComponent_26_4,[([] as any[]).concat([
        this._text_27,
        this._el_28,
        this._text_30,
        this._el_31,
        this._text_33,
        this._el_34,
        this._text_36
      ]
    )],(null as any));
    this._text_37 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_38 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_4; }
    if (((token === import11.ItemComponent) && ((8 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ItemComponent_8_4; }
    if (((token === import11.ItemComponent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._ItemComponent_13_4; }
    if (((token === import11.ItemComponent) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._ItemComponent_16_4; }
    if (((token === import10.AccordionComponent) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._AccordionComponent_6_4; }
    if (((token === import12.Item2Component) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Item2Component_28_4; }
    if (((token === import12.Item2Component) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Item2Component_31_4; }
    if (((token === import12.Item2Component) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Item2Component_34_4; }
    if (((token === import10.AccordionComponent) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._AccordionComponent_26_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = 'title 1';
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._ItemComponent_8_4.title = currVal_0;
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = 'title 2';
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ItemComponent_13_4.title = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = 'title 3';
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._ItemComponent_16_4.title = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = 'title 1';
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._Item2Component_28_4.title = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = 'title 2';
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._Item2Component_31_4.title = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = 'title 3';
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._Item2Component_34_4.title = currVal_5;
      this._expr_5 = currVal_5;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if ((this.numberOfChecks === 0)) { this._Item2Component_28_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Item2Component_31_4.ngAfterViewInit(); }
      if ((this.numberOfChecks === 0)) { this._Item2Component_34_4.ngAfterViewInit(); }
    }
  }
  destroyInternal():void {
    this._Item2Component_28_4.ngOnDestroy();
    this._Item2Component_31_4.ngOnDestroy();
    this._Item2Component_34_4.ngOnDestroy();
  }
}
export function viewFactory_AccordionDemoComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.AccordionDemoComponent> {
  if ((renderType_AccordionDemoComponent === (null as any))) { (renderType_AccordionDemoComponent = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_AccordionDemoComponent,{})); }
  return new _View_AccordionDemoComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_AccordionDemoComponent1 extends import1.AppView<any> {
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_AccordionDemoComponent1,renderType_AccordionDemoComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this.init(([] as any[]),([] as any[]),([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_AccordionDemoComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_AccordionDemoComponent1(viewUtils,parentInjector,declarationEl);
}