/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../../app/demos/accordion/item-no-tick.component';
const styles_Item2Component:any[] = ['[_nghost-%COMP%]{ display: block; }'];
export const RenderType_Item2Component:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_Item2Component,
  data: {}
}
);
function View_Item2Component_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),6,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n        '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'div',[[
        'class',
        'panel-body'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n            '])),
    import0.ɵncd((null as any),0),
    (l()(),import0.ɵted((null as any),['\n        '])),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(null as any),(null as any));
}
export function View_Item2Component_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵqud(201326592,1,{head: 0}),
    (l()(),import0.ɵted((null as any),['\n'])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),10,'div',[[
        'class',
        'panel panel-default'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵeld(0,[
      [
        1,
        0
      ]
      ,
      [
        'head',
        1
      ]

    ]
      ,(null as any),4,'div',[[
        'class',
        'panel-heading'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n        '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h4',[[
        'class',
        'panel-title'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '\n            ',
      '\n        '
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_Item2Component_1)),
    import0.ɵdid(8192,(null as any),0,import1.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(ck,v) => {
    var co:import2.Item2Component = v.component;
    const currVal_1:any = co.isActive;
    ck(v,11,0,currVal_1);
  },(ck,v) => {
    var co:import2.Item2Component = v.component;
    const currVal_0:any = co.title;
    ck(v,7,0,currVal_0);
  });
}
function View_Item2Component_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'item2',([] as any[]),(null as any),(null as any),(null as any),View_Item2Component_0,RenderType_Item2Component)),
    import0.ɵdid(2318336,(null as any),0,import2.Item2Component,[
      import0.ElementRef,
      import0.Renderer2,
      import0.NgZone,
      import0.ChangeDetectorRef,
      import0.ApplicationRef
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const Item2ComponentNgFactory:import0.ComponentFactory<import2.Item2Component> = import0.ɵccf('item2',import2.Item2Component,View_Item2Component_Host_0,{title: 'title'},{},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvRXlhbC9EZXNrdG9wL1BlcmZvcm1hbmNlIE9wdGltaXphdGlvbi9uZy1jb3Vyc2UoY2QpL2FwcC9kZW1vcy9hY2NvcmRpb24vaXRlbS1uby10aWNrLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9FeWFsL0Rlc2t0b3AvUGVyZm9ybWFuY2UgT3B0aW1pemF0aW9uL25nLWNvdXJzZShjZCkvYXBwL2RlbW9zL2FjY29yZGlvbi9pdGVtLW5vLXRpY2suY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvRXlhbC9EZXNrdG9wL1BlcmZvcm1hbmNlIE9wdGltaXphdGlvbi9uZy1jb3Vyc2UoY2QpL2FwcC9kZW1vcy9hY2NvcmRpb24vaXRlbS1uby10aWNrLmNvbXBvbmVudC50cy5JdGVtMkNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvRXlhbC9EZXNrdG9wL1BlcmZvcm1hbmNlIE9wdGltaXphdGlvbi9uZy1jb3Vyc2UoY2QpL2FwcC9kZW1vcy9hY2NvcmRpb24vaXRlbS1uby10aWNrLmNvbXBvbmVudC50cy5JdGVtMkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuPGRpdiBjbGFzcz1cInBhbmVsIHBhbmVsLWRlZmF1bHRcIj5cbiAgICA8ZGl2ICNoZWFkIGNsYXNzPVwicGFuZWwtaGVhZGluZ1wiPlxuICAgICAgICA8aDQgY2xhc3M9XCJwYW5lbC10aXRsZVwiPlxuICAgICAgICAgICAge3t0aXRsZX19XG4gICAgICAgIDwvaDQ+XG4gICAgPC9kaXY+XG4gICAgPGRpdiAqbmdJZj1cImlzQWN0aXZlXCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJwYW5lbC1ib2R5XCI+XG4gICAgICAgICAgICA8bmctY29udGVudD48L25nLWNvbnRlbnQ+XG4gICAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuPC9kaXY+XG4iLCI8aXRlbTI+PC9pdGVtMj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ09JO0lBQXNCO01BQ2xCO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBd0I7Z0JBQ3BCO0lBQXlCO0lBQ3ZCOzs7Ozs7O0lBVmQ7TUFDQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQWlDO0lBQzdCO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7T0FBQTtRQUFBO1FBQUE7TUFBQTtJQUFBO0lBQWlDO01BQzdCO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBd0I7TUFBQTtNQUFBO0lBQUE7SUFBQTtJQUVuQjtJQUNIO0lBQ047Z0JBQUE7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUlNO0lBQ0o7Ozs7SUFMRztJQUFMLFVBQUssU0FBTDs7O0lBSjRCO0lBQUE7Ozs7O0lDSGhDO2dCQUFBOzs7Ozs7SUFBQTtLQUFBOzs7SUFBQTs7OyJ9
